# Generated by Django 5.0.6 on 2025-05-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessions',
            old_name='mentee_id',
            new_name='mentee',
        ),
        migrations.RenameField(
            model_name='sessions',
            old_name='mentor_id',
            new_name='mentor',
        ),
    ]
