# Generated by Django 5.0.6 on 2025-05-09 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rename_mentee_id_sessions_mentee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='mentor',
        ),
        migrations.AddField(
            model_name='sessions',
            name='mentee',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessions',
            name='mentor',
            field=models.ManyToManyField(related_name='mentor', to=settings.AUTH_USER_MODEL),
        ),
    ]
