# Generated by Django 5.0.6 on 2025-05-10 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_sessions_mentee_remove_sessions_mentor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='mentee',
            field=models.ManyToManyField(related_name='mentee_session', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='mentor',
            field=models.ManyToManyField(related_name='mentor_session', to=settings.AUTH_USER_MODEL),
        ),
    ]
