# Generated by Django 5.0.6 on 2025-05-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_sessions_mentee_alter_sessions_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_skills',
            name='proficiency_level',
        ),
        migrations.RemoveField(
            model_name='user_skills',
            name='years_of_experience',
        ),
    ]
