# Generated by Django 5.0.6 on 2025-05-17 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_remove_user_skills_proficiency_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='slots',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_time', models.TextField()),
                ('to_time', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mentorSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
