# Generated by Django 5.0.6 on 2025-05-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_skills',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
